# Generated by Django 4.1.4 on 2023-04-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Enter your Username', max_length=20, unique=True)),
                ('First_name', models.CharField(help_text='Enter your First name', max_length=20)),
                ('Last_name', models.CharField(help_text='Enter your Last name', max_length=20)),
                ('phone', models.IntegerField(max_length=10, unique=True)),
                ('email', models.EmailField(help_text='Enter your Email', max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_donor', models.BooleanField(default=True)),
                ('is_NGO', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
