# Generated by Django 4.1.4 on 2023-04-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload your Profile Photo', null=True, upload_to='Profile-Pic/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_name',
            field=models.CharField(blank=True, help_text='Enter your First name', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_name',
            field=models.CharField(blank=True, help_text='Enter your Last name', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your Email', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Enter your Username', max_length=20, unique=True),
        ),
    ]
