# Generated by Django 4.1.4 on 2023-04-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginReg', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, help_text='Enter your Password', max_length=20, unique=True),
        ),
    ]
