# Generated by Django 4.1.3 on 2023-04-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_domain', models.CharField(max_length=100)),
                ('about_us', models.TextField(blank=True, max_length=1000, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_volunteers', models.IntegerField()),
                ('no_of_donations', models.IntegerField()),
                ('no_of_ppl_helped', models.IntegerField()),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngo.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('desciption', models.TextField(max_length=500)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ngo.profile')),
            ],
        ),
    ]
