# Generated by Django 4.1.3 on 2023-04-07 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ngo', '0002_rename_desciption_feedback_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('ngo_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ngo.profile')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
