# Generated by Django 4.1.3 on 2023-04-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='ngo_name',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
