# Generated by Django 4.1.4 on 2023-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
