# Generated by Django 4.1.3 on 2023-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_alter_profile_address_alter_profile_company_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fbanalysis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
