# Generated by Django 4.1.4 on 2023-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
        migrations.AddField(
            model_name='community',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
