# Generated by Django 4.1.4 on 2023-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_community_user_community_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='username',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
