# Generated by Django 4.1.4 on 2023-04-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_community_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='money',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='money_currency',
        ),
    ]
